# /config/www/home-floorplan/floorplan_config.yaml

rules:
  # TRACCIA DEL CONFIG: Se vedi questo, il file config viene letto ed esiste!
  - name: "Verifica Lettura Config"
    entities:
      - sun.sun
    element:
      - layer_seminterrato
    state_action:
      action: call-service
      service: floorplan.class_set
      service_data: ${ console.log("[STEP 1] - floorplan_config.yaml È STATO LETTO CON SUCCESSO!") || "layer-visible" }

# Modo standard di Floorplan per includere file esterni nel browser (sottopagine di regole)
pages:
  - /local/home-floorplan/floorplan_rules.yaml